version: 2.1

executors:
  python-terraform-executor:
    docker:
      - image: cimg/deploy:2025.01
      - image: cimg/python:3.13
jobs:
  publish:
    executor: python-terraform-executor
    steps:
      - checkout
      - run:
          name: install golang 1.24.1
          command: wget https://go.dev/dl/go1.24.1.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.24.1.linux-amd64.tar.gz && export PATH=$PATH:/usr/local/go/bin
      - run:
          name: verify go
          command: go version
      - run:
          name: verify terraform
          command: terraform version
      - run:
          name: verify python
          command: python --version
      - run:
          name: python compile_lambda.py
          command: python compile_lambda.py
      - run:
          name: python terraform_init.py
          command: python terraform_init.py
      - run:
          name: python terraform_format.py
          command: python terraform_format.py

workflows:
  main:
    jobs:
      - publish