version: 2.1

executors:
  python-terraform-executor:
    docker:
      - image: cimg/python
      - image: cimg/terraform

jobs:
  publish:
    executor: python-terraform-executor
    steps:
      - checkout
      - run:
          name: Execute Python Script
          command: terraform fmt

workflows:
  main:
    jobs:
      - publish