version: 2.1

orbs:
  python: circleci/python@3.0.0
  terraform: circleci/terraform@3.6.0

jobs:
  publish:
    executor: python/default
    docker:
      - hashicorp/terraform:light
    steps:
      - checkout
      - run: python terraform_format.py
workflows:
  main:
    jobs:
      - publish
