version: 2.1

executors:
  python-terraform-executor:
    docker:
      - image: cimg/deploy:2025.01
      - image: cimg/python:3.13
jobs:
  publish:
    executor: python-terraform-executor
    steps:
      - checkout
      - run:
          name: go
          command: sudo apt update -y && sudo apt install golang -y
      - run:
          name: asdf
          command: go env
      - run:
          name: verify terraform
          command: terraform version
      - run:
          name: verify python
          command: python --version
      - run:
          name: python compile_lambda.py
          command: python compile_lambda.py
      - run:
          name: python terraform_init.py
          command: python terraform_init.py
      - run:
          name: python terraform_format.py
          command: python terraform_format.py

workflows:
  main:
    jobs:
      - publish