version: 2.1

executors:
  python-terraform-executor:
    docker:
      - image: cimg/deploy:2025.01
      - image: cimg/python:3.13.2

jobs:
  publish:
    executor: python-terraform-executor
    steps:
      - checkout
      - run:
          name: terraform init
          command: python terraform_init.py
      - run:
          name: terraform format
          command: python terraform_format.py

workflows:
  main:
    jobs:
      - publish