version: 2.1

executors:
  deploy-executor:
    docker:
      - image: cimg/deploy:2025.01
jobs:
  publish:
    executor: deploy-executor
    parallelism: 1
    steps:
      - checkout
      - run:
          name: update machine
          command: sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove -y
      - run:
          name: install golang
          command: |
            wget https://go.dev/dl/go1.24.1.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.24.1.linux-amd64.tar.gz
            echo 'export PATH=$PATH:/usr/local/go/bin' >> $BASH_ENV
      - run:
          name: verify golang
          command: go version
      - run:
          name: verify terraform
          command: terraform version
      - run:
          name: verify python
          command: python --version
      - run:
          name: python compile_lambda.py
          command: python compile_lambda.py
      - restore_cache:
          keys:
            - terraform_state_key
      - run:
          name: python terraform_init.py
          command: python terraform_init.py
      - save_cache:
          name: Terraform state caching in CircleCI
          key: terraform_state_key
          paths:
            - app/.terraform
            - app/terraform.tfstate
            - app/terraform.lock.hcl

workflows:
  main:
    jobs:
      - publish