version: 2.1

executors:
  python-terraform-executor:
    docker:
      - image: cimg/deploy:2025.01
jobs:
  publish:
    executor: python-terraform-executor
    steps:
      - checkout
      - run:
          name: update machine
          command: sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove -y
      - run:
          name: install golang
          command: |
            wget https://go.dev/dl/go1.24.1.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.24.1.linux-amd64.tar.gz
            echo 'export PATH=$PATH:/usr/local/go/bin' >> $BASH_ENV
      - run:
          name: verify golang
          command: go version
      - run:
          name: verify terraform
          command: terraform version
      - run:
          name: verify python
          command: python --version
      - run:
          name: python compile_lambda.py
          command: python compile_lambda.py
      - run:
          name: python terraform_init.py
          command: python terraform_init.py
      - run:
          name: python terraform_format.py
          command: python terraform_format.py

workflows:
  main:
    jobs:
      - publish