version: 2.1

workflows:
  main:
    when:
      and:
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - compile-go-lambda:
          name: Compile Golang for AWS Lambda deployment
      - terraform-plan:
          name: Create Terraform Plan
          serial-group: << pipeline.project.slug >>/terraform-plan-group
          requires:
            - Compile Golang for AWS Lambda deployment
      - hold:
          name: Verify the Terraform plan
          serial-group: << pipeline.project.slug >>/terraform-verify-group
          type: approval
          requires:
            - Create Terraform Plan
      - terraform-apply:
          name: Apply the Terraform plan to AWS
          requires:
            - Verify the Terraform plan
executors:
  golang-executor:
    docker:
      - image: cimg/go:1.24.1
  deploy-executor:
    docker:
      - image: cimg/deploy:2025.01
jobs:
  compile-go-lambda:
    executor: golang-executor
    steps:
      - checkout
      - run:
          name: Verify golang
          command: go version
      - run:
          name: Verify python
          command: python --version
      - run:
          name: Compile Golang
          command: python compile_lambda.py
      - persist_to_workspace:
          name: Persist Lambda binaries to CircleCI Workspace
          root: .
          paths:
            - app/lambda_src/hello/bootstrap
  terraform-plan:
    executor: deploy-executor
    steps:
      - checkout
      - attach_workspace:
          name: Attach CircleCI workspace
          at: .
      - run:
          name: Verify Terraform
          command: terraform version
      - run:
          name: Verify Python
          command: python --version
      - run:
          name: Terraform Init
          command: python terraform_init.py
      - run:
          name: Terraform Plan
          command: python terraform_plan.py
      - persist_to_workspace:
          name: Persist Lambda zip files to CircleCI Workspace
          root: .
          paths:
            - app/hello-bootstrap.zip
      - persist_to_workspace:
          name: Persist 'pokedex-tfplan' to CircleCI Workspace
          root: .
          paths:
            - app/pokedex-tfplan
  terraform-apply:
    executor: deploy-executor
    steps:
      - checkout
      - attach_workspace:
          name: Attach CircleCI workspace
          at: .
      - run:
          name: Verify Terraform
          command: terraform version
      - run:
          name: Verify Python
          command: python --version
      - run:
          name: Terraform Init
          command: python terraform_init.py
      - run:
          name: Terraform Apply
          command: python terraform_apply.py


