version: 2.1


orbs:
  terraform: circleci/terraform@3.6.0

jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - run:
          name: install golang
          command: |
            wget https://go.dev/dl/go1.24.1.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.24.1.linux-amd64.tar.gz
            echo 'export PATH=$PATH:/usr/local/go/bin' >> $BASH_ENV
      - run:
          name: verify golang
          command: go version
      - run:
          name: verify python
          command: python --version
      - run:
          name: python compile_lambda.py
          command: python compile_lambda.py
      - run:
          name: Set up AWS Secrets
          command: |
            cat \<<EOF > app/vars/secret.tfvars.tf
                aws_access_key = "$AWS_ACCESS_KEY"
                aws_secret_key = "$AWS_SECRET_KEY"
            EOF
      - terraform/init:
          path: app
      - terraform/validate:
          path: app
      - terraform/fmt:
          path: app
      - terraform/plan:
          path: app
      - terraform/apply:
          path: app
      - terraform/plan:
          destroy_plan: true
          path: app
      - terraform/destroy:
          path: app

workflows:
  main:
    jobs:
      - publish