version: 2.1

executors:
  python-terraform-executor:
    docker:
      - image: cimg/deploy:2025.01
      - image: cimg/go:1.24.1
      - image: cimg/python:3.13.2

jobs:
  publish:
    executor: python-terraform-executor
    steps:
      - checkout
      - run:
          name: asdf
          command: which go
      - run:
          name: terraform
          command: terraform version
      - run:
          name: python
          command: python --version
      - run:
          name: go
          command: go version
      - run:
          name: python compile_lambda.py
          command: python compile_lambda.py
      - run:
          name: python terraform_init.py
          command: python terraform_init.py
      - run:
          name: python terraform_format.py
          command: python terraform_format.py

workflows:
  main:
    jobs:
      - publish